function experiment = applyMetadata(experiment, xlsxPath)
% Reads a filled-in metadata Excel template and merges it into the
% experiment struct. Any columns you add to the Recordings sheet beyond
% the defaults automatically become new fields in recording.metadata.
%
% Usage:
%   experiment = applyMetadata(experiment);
%   experiment = applyMetadata(experiment, 'path/to/experiment_metadata.xlsx');
%
% After applying, save with:
%   save('experiment.mat', 'experiment');
%
% Excel format (generated by loadABFDirectory):
%   Sheet "Recordings"  - one row per .abf file; add any extra metadata columns here
%   Sheet "DayNotes"    - one row per recording day; fill in the dayNotes column

if nargin < 2
    [f, p] = uigetfile('*.xlsx', 'Select metadata Excel file');
    if isequal(f, 0)
        error('No file selected.');
    end
    xlsxPath = fullfile(p, f);
end

T1 = readtable(xlsxPath, 'Sheet', 'Recordings', 'TextType', 'string');
T2 = readtable(xlsxPath, 'Sheet', 'DayNotes',   'TextType', 'string');

% Apply day-level notes
for i = 1:numel(experiment)
    mask = strcmp(T2.date, experiment(i).date);
    if any(mask)
        experiment(i).notes = char(T2.dayNotes(find(mask, 1)));
    end
end

% Metadata columns are everything in the Recordings sheet beyond the
% fixed identifier columns. Extra columns added by the user are included
% automatically.
fixedCols = {'date', 'filename', 'expNumber'};
allCols   = T1.Properties.VariableNames;
metaCols  = allCols(~ismember(allCols, fixedCols));

nApplied = 0;
nMissing = 0;

for i = 1:numel(experiment)
    for j = 1:numel(experiment(i).recordings)
        fname = experiment(i).recordings(j).filename;
        row   = T1(strcmp(T1.filename, fname), :);

        if isempty(row)
            warning('applyMetadata:missingRow', ...
                'No metadata row found for: %s', fname);
            nMissing = nMissing + 1;
            continue;
        end

        for c = 1:numel(metaCols)
            col   = metaCols{c};
            val   = row.(col)(1);
            if isstring(val)
                val = char(val);
            end
            field = matlab.lang.makeValidName(col);
            experiment(i).recordings(j).metadata.(field) = val;
        end
        nApplied = nApplied + 1;
    end
end

fprintf('Metadata applied to %d recording(s)', nApplied);
if nMissing > 0
    fprintf(' (%d missing rows in Excel)', nMissing);
end
fprintf('.\nRemember to save:  save(''experiment.mat'', ''experiment'');\n');
end
